### ISSUE TITLE
Need to add sources and javadocs to JCenter release

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/pelias-client-library#13]
I received this message when trying to publish v1.0.0 release to JCenter:

> Hi, JCenter hosts java applications that follow maven convention. In addition to the .pom file, your version should include a binary jar file, a sources jar, and optionally a javadoc jar. Your files should be under a maven path layout. (See https://bintray.com/docs/usermanual/uploads/uploads_includingyourpackagesinjcenter.html) Once those files are added, we'll be glad to include your package in JCenter Regards, JFrog Support

**Comment by tangyong3g** [comment]
How did you solve this problem?

**Comment by barbeau** [comment]
See https://github.com/CUTR-at-USF/pelias-client-library/commit/69f551cf79050a90a6d37d2bb3c358b97eec63fb
