### ISSUE TITLE
Fix README

### ISSUE THREAD

**Issue by jmfield2** [CUTR-at-USF/pelias-client-library#4]
The README currently lists the pelias package as 'edu.usf.cutr.pelias' - related to #2 - update this to reflect the actual name.

Also, the raw github URLs have changed to use raw.githubusercontent.com instead.  The other urls don't work directly.

**Comment by barbeau** [comment]
Thanks @jmfield2!  #10 is the proper fix for the package name issue, and I'll push a separate commit shortly for the Github URLs.
